---
- name: reload prometheus
  community.docker.docker_container_exec:
    container: pulse-prometheus
    command: |
      sh -c "wget -q --post-data='' -O- http://localhost:9090/-/reload || true"
  ignore_errors: yes