---
- name: reload prometheus
  community.docker.docker_container_exec:
    container: pulse-prometheus
    command: |
      sh -c "wget -q --method=POST http://localhost:9090/-/reload && echo reloaded"
  ignore_errors: yes   # Ignore errors in case Prometheus isn't running yet (e.g. first run)