---
- name: Deploy pulse-backend
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker image to host
      copy:
        src: /var/jenkins_home/workspace/pulse/pulse-backend.tar
        dest: /tmp/pulse-backend.tar

    - name: Load Docker image
      shell: docker load -i /tmp/pulse-backend.tar

    - name: Stop existing container
      community.docker.docker_container:
        name: pulse-backend
        state: absent

    - name: Run pulse-backend container
      community.docker.docker_container:
        name: pulse-backend
        image: pulse-backend:latest
        state: started
        ports:
          - "80:5000"
        restart_policy: always