---
- name: Deploy pulse services
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy backend Docker image
      copy:
        src: /var/jenkins_home/workspace/pulse/pulse-backend.tar
        dest: /tmp/pulse-backend.tar

    - name: Load backend Docker image
      shell: docker load -i /tmp/pulse-backend.tar

    - name: Stop existing backend container
      community.docker.docker_container:
        name: pulse-backend
        state: absent

    - name: Run backend container
      community.docker.docker_container:
        name: pulse-backend
        image: pulse-backend:latest
        state: started
        ports:
          - "80:5000"
        restart_policy: always

    - name: Copy frontend Docker image
      copy:
        src: /var/jenkins_home/workspace/pulse/pulse-frontend.tar
        dest: /tmp/pulse-frontend.tar

    - name: Load frontend Docker image
      shell: docker load -i /tmp/pulse-frontend.tar

    - name: Stop existing frontend container
      community.docker.docker_container:
        name: pulse-frontend
        state: absent

    - name: Run frontend container
      community.docker.docker_container:
        name: pulse-frontend
        image: pulse-frontend:latest
        state: started
        ports:
          - "8080:8080"
        restart_policy: always